//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 06:28:31 AM IST 
//


package generated;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sources_QNAME = new QName("", "sources");
    private final static QName _ApparentTemperatureMinTime_QNAME = new QName("", "apparentTemperatureMinTime");
    private final static QName _Timezone_QNAME = new QName("", "timezone");
    private final static QName _TemperatureMax_QNAME = new QName("", "temperatureMax");
    private final static QName _Latitude_QNAME = new QName("", "latitude");
    private final static QName _Icon_QNAME = new QName("", "icon");
    private final static QName _WindBearing_QNAME = new QName("", "windBearing");
    private final static QName _PrecipIntensityMax_QNAME = new QName("", "precipIntensityMax");
    private final static QName _ApparentTemperature_QNAME = new QName("", "apparentTemperature");
    private final static QName _Units_QNAME = new QName("", "units");
    private final static QName _Ozone_QNAME = new QName("", "ozone");
    private final static QName _ApparentTemperatureMin_QNAME = new QName("", "apparentTemperatureMin");
    private final static QName _TemperatureMaxTime_QNAME = new QName("", "temperatureMaxTime");
    private final static QName _SunsetTime_QNAME = new QName("", "sunsetTime");
    private final static QName _IsdStations_QNAME = new QName("", "isd-stations");
    private final static QName _Temperature_QNAME = new QName("", "temperature");
    private final static QName _PrecipType_QNAME = new QName("", "precipType");
    private final static QName _Humidity_QNAME = new QName("", "humidity");
    private final static QName _WindSpeed_QNAME = new QName("", "windSpeed");
    private final static QName _MoonPhase_QNAME = new QName("", "moonPhase");
    private final static QName _SunriseTime_QNAME = new QName("", "sunriseTime");
    private final static QName _Longitude_QNAME = new QName("", "longitude");
    private final static QName _Summary_QNAME = new QName("", "summary");
    private final static QName _PrecipProbability_QNAME = new QName("", "precipProbability");
    private final static QName _Offset_QNAME = new QName("", "offset");
    private final static QName _PrecipIntensity_QNAME = new QName("", "precipIntensity");
    private final static QName _CloudCover_QNAME = new QName("", "cloudCover");
    private final static QName _TemperatureMin_QNAME = new QName("", "temperatureMin");
    private final static QName _Pressure_QNAME = new QName("", "pressure");
    private final static QName _DewPoint_QNAME = new QName("", "dewPoint");
    private final static QName _TemperatureMinTime_QNAME = new QName("", "temperatureMinTime");
    private final static QName _ApparentTemperatureMax_QNAME = new QName("", "apparentTemperatureMax");
    private final static QName _PrecipAccumulation_QNAME = new QName("", "precipAccumulation");
    private final static QName _Time_QNAME = new QName("", "time");
    private final static QName _PrecipIntensityMaxTime_QNAME = new QName("", "precipIntensityMaxTime");
    private final static QName _ApparentTemperatureMaxTime_QNAME = new QName("", "apparentTemperatureMaxTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Flags }
     * 
     */
    public Flags createFlags() {
        return new Flags();
    }

    /**
     * Create an instance of {@link WeatherData }
     * 
     */
    public WeatherData createWeatherData() {
        return new WeatherData();
    }

    /**
     * Create an instance of {@link Currently }
     * 
     */
    public Currently createCurrently() {
        return new Currently();
    }

    /**
     * Create an instance of {@link Daily }
     * 
     */
    public Daily createDaily() {
        return new Daily();
    }

    /**
     * Create an instance of {@link Hourly }
     * 
     */
    public Hourly createHourly() {
        return new Hourly();
    }

    /**
     * Create an instance of {@link Weather }
     * 
     */
    public Weather createWeather() {
        return new Weather();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sources")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSources(String value) {
        return new JAXBElement<String>(_Sources_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apparentTemperatureMinTime")
    public JAXBElement<BigInteger> createApparentTemperatureMinTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_ApparentTemperatureMinTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timezone")
    public JAXBElement<String> createTimezone(String value) {
        return new JAXBElement<String>(_Timezone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperatureMax")
    public JAXBElement<BigDecimal> createTemperatureMax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TemperatureMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "latitude")
    public JAXBElement<BigDecimal> createLatitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Latitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "icon")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIcon(String value) {
        return new JAXBElement<String>(_Icon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "windBearing")
    public JAXBElement<BigInteger> createWindBearing(BigInteger value) {
        return new JAXBElement<BigInteger>(_WindBearing_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "precipIntensityMax")
    public JAXBElement<BigDecimal> createPrecipIntensityMax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PrecipIntensityMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apparentTemperature")
    public JAXBElement<BigDecimal> createApparentTemperature(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ApparentTemperature_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "units")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUnits(String value) {
        return new JAXBElement<String>(_Units_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ozone")
    public JAXBElement<BigDecimal> createOzone(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Ozone_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apparentTemperatureMin")
    public JAXBElement<BigDecimal> createApparentTemperatureMin(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ApparentTemperatureMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperatureMaxTime")
    public JAXBElement<BigInteger> createTemperatureMaxTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_TemperatureMaxTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sunsetTime")
    public JAXBElement<BigInteger> createSunsetTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_SunsetTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isd-stations")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIsdStations(String value) {
        return new JAXBElement<String>(_IsdStations_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperature")
    public JAXBElement<BigDecimal> createTemperature(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Temperature_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "precipType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrecipType(String value) {
        return new JAXBElement<String>(_PrecipType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "humidity")
    public JAXBElement<BigDecimal> createHumidity(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Humidity_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "windSpeed")
    public JAXBElement<BigDecimal> createWindSpeed(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_WindSpeed_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "moonPhase")
    public JAXBElement<BigDecimal> createMoonPhase(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MoonPhase_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sunriseTime")
    public JAXBElement<BigInteger> createSunriseTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_SunriseTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "longitude")
    public JAXBElement<BigDecimal> createLongitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Longitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "precipProbability")
    public JAXBElement<BigDecimal> createPrecipProbability(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PrecipProbability_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "offset")
    public JAXBElement<BigInteger> createOffset(BigInteger value) {
        return new JAXBElement<BigInteger>(_Offset_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "precipIntensity")
    public JAXBElement<Double> createPrecipIntensity(Double value) {
        return new JAXBElement<Double>(_PrecipIntensity_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cloudCover")
    public JAXBElement<BigDecimal> createCloudCover(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CloudCover_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperatureMin")
    public JAXBElement<BigDecimal> createTemperatureMin(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TemperatureMin_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pressure")
    public JAXBElement<BigDecimal> createPressure(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Pressure_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dewPoint")
    public JAXBElement<BigDecimal> createDewPoint(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DewPoint_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "temperatureMinTime")
    public JAXBElement<BigInteger> createTemperatureMinTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_TemperatureMinTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apparentTemperatureMax")
    public JAXBElement<BigDecimal> createApparentTemperatureMax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ApparentTemperatureMax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "precipAccumulation")
    public JAXBElement<BigDecimal> createPrecipAccumulation(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PrecipAccumulation_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time")
    public JAXBElement<BigInteger> createTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_Time_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "precipIntensityMaxTime")
    public JAXBElement<BigInteger> createPrecipIntensityMaxTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_PrecipIntensityMaxTime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apparentTemperatureMaxTime")
    public JAXBElement<BigInteger> createApparentTemperatureMaxTime(BigInteger value) {
        return new JAXBElement<BigInteger>(_ApparentTemperatureMaxTime_QNAME, BigInteger.class, null, value);
    }

}
