//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 06:28:31 AM IST 
//


package com.weather.service;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}offset"/>
 *         &lt;element ref="{}currently"/>
 *         &lt;element ref="{}timezone"/>
 *         &lt;element ref="{}latitude"/>
 *         &lt;element ref="{}daily"/>
 *         &lt;element ref="{}flags"/>
 *         &lt;element ref="{}hourly"/>
 *         &lt;element ref="{}longitude"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offset",
    "currently",
    "timezone",
    "latitude",
    "daily",
    "flags",
    "hourly",
    "longitude"
})
@XmlRootElement(name = "WeatherData")
public class WeatherData {

    @XmlElement(required = true)
    protected BigInteger offset;
    @XmlElement(required = true)
    protected Currently currently;
    @XmlElement(required = true)
    protected String timezone;
    @XmlElement(required = true)
    protected BigDecimal latitude;
    @XmlElement(required = true)
    protected Daily daily;
    @XmlElement(required = true)
    protected Flags flags;
    @XmlElement(required = true)
    protected Hourly hourly;
    @XmlElement(required = true)
    protected BigDecimal longitude;

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffset(BigInteger value) {
        this.offset = value;
    }

    /**
     * Gets the value of the currently property.
     * 
     * @return
     *     possible object is
     *     {@link Currently }
     *     
     */
    public Currently getCurrently() {
        return currently;
    }

    /**
     * Sets the value of the currently property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currently }
     *     
     */
    public void setCurrently(Currently value) {
        this.currently = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the daily property.
     * 
     * @return
     *     possible object is
     *     {@link Daily }
     *     
     */
    public Daily getDaily() {
        return daily;
    }

    /**
     * Sets the value of the daily property.
     * 
     * @param value
     *     allowed object is
     *     {@link Daily }
     *     
     */
    public void setDaily(Daily value) {
        this.daily = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link Flags }
     *     
     */
    public Flags getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flags }
     *     
     */
    public void setFlags(Flags value) {
        this.flags = value;
    }

    /**
     * Gets the value of the hourly property.
     * 
     * @return
     *     possible object is
     *     {@link Hourly }
     *     
     */
    public Hourly getHourly() {
        return hourly;
    }

    /**
     * Sets the value of the hourly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hourly }
     *     
     */
    public void setHourly(Hourly value) {
        this.hourly = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

}
